### PR TITLE
Improve method documentation

### PR DESCRIPTION
**Pull request by j8r**
Change also the organization from NeuralLegion to crystal-community

### CODE REVIEW

**Comment by bararchy** [comment]
Looks great, I should have changed the readme , good catch !

**Comment by bararchy** [comment]
@hugoabonizio or @veelenga 
Can you make me admin of this repo so that I could help with review and merging? 

Thanks,

**Comment by veelenga** [comment]
@bararchy done. Sorry, forgot to do it at the beginning :)

**Comment by bararchy** [comment]
@veelenga all good, thanks :)

**Pull request merged**
